/* =====================================================================
   NAVIDIX — the curriculum, as data.

   Generated by tools/curriculum.py. Do not edit by hand: the next build
   overwrites it. Add or move a lesson in that file instead, and both this
   and journey.html come out in step.

   Read by nvx-progress.js and by journey.html. A page that never loads
   this file is untouched by any of it.
   ===================================================================== */
window.NVX_CURRICULUM = {
  total: 14,
  minutes: 560,
  stages: [
    {id:'fundamentals',no:'۰۱',en:'AI Fundamentals',fa:'مبانی هوش مصنوعی',lessons:[{slug:'ai-start',t:'از کجا شروع کنم؟ راهنمای صفرِ صفر',s:'شروع از صفر',min:40}]},
    {id:'prompting',no:'۰۲',en:'Prompt Engineering',fa:'پرامپت‌نویسی',lessons:[{slug:'ai-prompting',t:'چطور درست بپرسم؟ آناتومی یک پرامپت خوب',s:'آناتومی پرامپت',min:45}]},
    {id:'image',no:'۰۳',en:'AI Image Generation',fa:'تولید تصویر',lessons:[{slug:'ai-image-sound',t:'تصویر و صدا: ساختن، خواندن، شنیدن',s:'تصویر و صدا',min:40},{slug:'light-composition',t:'نور و ترکیب‌بندی: ساختن حس با نور و قاب',s:'نور و ترکیب‌بندی',min:45}]},
    {id:'video',no:'۰۴',en:'AI Video Generation',fa:'تولید ویدیو',lessons:[{slug:'camera-language',t:'زبان دوربین: زاویه، اندازه‌ی نما و حرکت',s:'زبان دوربین',min:35},{slug:'video-motion',t:'پرامپت‌نویسی ویدیو: از قاب ثابت تا حرکت کنترل‌شده',s:'پرامپت ویدیو',min:40}]},
    {id:'story',no:'۰۵',en:'Cinematic Storytelling',fa:'روایت سینمایی',lessons:[{slug:'idea-to-final',t:'از ایده تا نمای نهایی: هفت مرحله‌ی تولید',s:'ایده تا نمای نهایی',min:40},{slug:'edit-sound',t:'تدوین و صدا',s:'تدوین و صدا',min:35}]},
    {id:'direction',no:'۰۶',en:'Creative Direction',fa:'مدیریت خلاق',lessons:[{slug:'ai-systems',t:'از یک کار به یک سیستم',s:'از کار تا سیستم',min:45},{slug:'ai-first-project',t:'اولین کارِ واقعی',s:'اولین کار واقعی',min:40},{slug:'brand-content',t:'برند، پیش از محتوا',s:'برند پیش از محتوا',min:50},{slug:'team-monetization',t:'تیم و درآمد: ساختن ماشین مقیاس‌پذیری',s:'تیم و درآمد',min:45},{slug:'rights-contracts',t:'مالِ کیست؟ حق، مجوز و قرارداد در کار با هوش مصنوعی',s:'حق و قرارداد',min:35},{slug:'hell-grind',t:'پرونده‌ی باز Hell Grind',s:'پرونده Hell Grind',min:25}]}
  ]
};
