# -*- coding: utf-8 -*-
"""The style data. Everything else — the index, the per-style pages, the
plates, the search index, the sitemap entries — is derived from this list.

Each entry carries a Style DNA rather than just a name, because a name is
not reusable: "Baroque" tells a model almost nothing, while the medium,
brushwork, palette, lighting, texture, composition and mood behind it can be
recombined with any subject and with each other.

plate = (mark-making, lighting, palette) and drives the generated artwork.
  mark: impasto | dabs | wash | flat | hatch | line | smooth | grain
  lit : chiaro | golden | soft | neon | rim | flat | top | back
"""

# False while prompts/*.jpg are the code-drawn abstract plates, True once they
# are real output of each style's own prompt. Only the caption under the image
# depends on it, and that caption is a claim about what you are looking at —
# so it moves when the pictures do. plates-import.py flips it.
PLATES_ARE_SAMPLES = True

CATS = [
    ('real',    'واقع‌گرایی و عکاسی',  'عکاسی و رئالیسم — از پرتره‌ی استودیویی تا قاب سینمایی.'),
    ('classic', 'نقاشی کلاسیک',        'از رنسانس تا رمانتیسم؛ سنت اروپایی رنگ روغن.'),
    ('modern',  'مدرن و انتزاعی',      'امپرسیونیسم به بعد؛ جایی که فرم از توصیف جدا می‌شود.'),
    ('trad',    'سنتی و شرقی',         'مینیاتور ایرانی، اوکیو-ئه، مرکب چینی و تذهیب.'),
    ('tech',    'متریال و تکنیک',      'خودِ ماده: آبرنگ، گواش، مرکب، مداد، چاپ دستی.'),
    ('light',   'نورپردازی سینمایی',   'نور را جدا از سبک انتخاب کن و با هر کدام ترکیبش کن.'),
]

def S(**k): return k

STYLES = [
# ── واقع‌گرایی و عکاسی ────────────────────────────────────────────────────
S(id='studio', cat='real', fa='پرتره‌ی استودیویی', en='Studio Portrait', period='معاصر',
  plate=('smooth','soft',['#1A1A1D','#6E6A66','#EADFD2']),
  dna=dict(medium='عکاسی دیجیتال، لنز ۸۵ میلی‌متری',
           brush='بدون ضربه‌قلم؛ گذارِ تُنِ پیوسته',
           light='یک سافت‌باکس بزرگ در زاویه‌ی ۴۵ درجه، نور مو از پشت',
           palette='خنثی و کم‌اشباع؛ پوست گرم روی پس‌زمینه‌ی زغالی',
           texture='بافت واقعی پوست حفظ‌شده، بدون رتوش پلاستیکی',
           comp='نیم‌تنه، فضای تنفس بالای سر، عمق میدان کم',
           mood='آرام، متمرکز، حرفه‌ای'),
  subject='a woman in her sixties with silver hair, wearing a charcoal wool coat',
  img='studio portrait photograph of {SUBJECT}, 85mm lens at f/1.8, large softbox key light at 45 degrees, subtle hair light from behind, seamless charcoal backdrop, shallow depth of field, crisp catchlight in the eyes, natural skin texture retained, neutral colour grade',
  vid='slow push-in portrait of {SUBJECT}, 85mm lens, shallow depth of field, single large softbox at 45 degrees holding steady, gentle hair light, subject breathing and blinking naturally, no camera shake, consistent exposure throughout, seamless dark backdrop',
  neg='plastic airbrushed skin, over-smoothed face, harsh direct flash, cluttered background, blown highlights, heavy vignette, oversaturated colour',
  recipe='پرتره‌ی استودیویی <b>زبان تجهیزات</b> دارد: لنز، دیافراگم و چیدمان نور. «85mm at f/1.8» فشردگی و بوکه‌ی درست می‌دهد. مهم‌ترین عبارت کل پرامپت «natural skin texture retained» است — بدون آن پوست پلاستیکی می‌شود.',
  tags='پرتره استودیو سافت‌باکس لنز بوکه پوست هدشات portrait studio softbox 85mm bokeh headshot'),

S(id='doc', cat='real', fa='عکاسی مستند و خیابانی', en='Documentary / Street', period='معاصر',
  plate=('grain','flat',['#3A3B38','#9C8C74','#D6D2CA']),
  dna=dict(medium='فیلم ۳۵ میلی‌متری یا دیجیتال، لنز ۳۵',
           brush='—', light='فقط نور موجود؛ هیچ منبع مصنوعی',
           palette='رنگ طبیعی و کم‌اشباع، نزدیک به واقعیت',
           texture='گرین آشکار فیلم',
           comp='کادر دستیِ ناکامل، لحظه‌ی بی‌قرار',
           mood='بی‌واسطه، صادق، ناتمام'),
  subject='a fruit seller reaching across his stall as a customer counts coins in a crowded morning market',
  img='candid documentary photograph of {SUBJECT}, 35mm lens, available light only, slight motion blur, imperfect handheld framing, real unposed expression, visible film grain, muted natural colour, photojournalism',
  vid='handheld documentary shot following {SUBJECT}, 35mm lens, available light only, natural camera sway and micro-corrections, subject unaware of camera, ambient street motion, film grain throughout, no stabilisation, no colour grading',
  neg='studio lighting, posed expression, perfectly level horizon, glossy retouching, staged composition, cinematic teal-orange grade',
  recipe='این سبک با <b>نقص</b> ساخته می‌شود نه با کیفیت. «imperfect handheld framing»، «slight motion blur» و «unposed» همان چیزهایی‌اند که خروجی را از حالت تبلیغاتی درمی‌آورند. «available light only» یعنی هیچ نور مصنوعی.',
  tags='مستند خیابانی فتوژورنالیسم کاندید گرین documentary street candid photojournalism grain'),

S(id='film35', cat='real', fa='قاب سینمایی ۳۵ میلی‌متری', en='Cinematic 35mm', period='معاصر',
  plate=('smooth','back',['#101820','#2F5D6B','#E0A26B']),
  dna=dict(medium='نگاتیو ۳۵ میلی‌متری، لنز آنامورفیک',
           brush='—', light='منبع نور داخل کادر، هاله‌ی نرم دور هایلایت',
           palette='گرید فیروزه‌ای–نارنجی، سایه‌های سرد',
           texture='گرین آلی فیلم، هالیشن دور نورها',
           comp='قاب عریض ۲.۳۹:۱، فوکوس کم‌عمق',
           mood='سینمایی، فاصله‌دار، باوقار'),
  subject='a young man alone at a night bus stop, lit shop signs behind him',
  img='cinematic 35mm film still of {SUBJECT}, anamorphic widescreen 2.39:1, shallow focus, teal and orange colour grade, subtle halation around highlights, organic film grain, practical lights visible in frame, Kodak Vision3 stock',
  vid='cinematic 35mm sequence of {SUBJECT}, anamorphic 2.39:1, slow dolly move, shallow focus with a deliberate rack to the subject, practical lights in frame, halation on highlights, consistent film grain, teal and orange grade held across the shot, 24fps motion cadence',
  neg='flat phone video look, digital sharpening halos, 16:9 crop, sterile even lighting, plastic HDR, over-stabilised gimbal glide',
  recipe='«film still» بنویس نه «photo» — مدل بلافاصله ترکیب‌بندی سینمایی می‌سازد. «halation» همان درخشش نرم دور نورهاست که حس آنالوگ می‌دهد، و «practical lights in frame» یعنی منبع نور داخل قاب دیده شود.',
  tags='سینمایی فیلم آنالوگ آنامورفیک گرید کداک cinematic 35mm anamorphic halation film grain'),

S(id='product', cat='real', fa='ماکرو محصول', en='Product Macro', period='معاصر',
  plate=('smooth','top',['#0E0F12','#4C5A66','#F5F7FA']),
  dna=dict(medium='عکاسی ماکرو، فوکوس‌استکینگ',
           brush='—', light='سافت‌باکس بزرگ از بالا، بازتاب کنترل‌شده',
           palette='خنثی و تمیز، پس‌زمینه‌ی گرادیانی',
           texture='سطح صیقلی با بازتاب نرم',
           comp='سوژه در مرکز، فضای خالی سخاوتمند',
           mood='دقیق، گران، کنترل‌شده'),
  subject='a brass mechanical wristwatch with a worn leather strap',
  img='high-end product photograph of {SUBJECT}, macro detail, gradient seamless background, large diffused softbox above, controlled specular highlights, subtle reflection on polished surface, tack sharp focus stacking, commercial advertising quality',
  vid='slow orbit around {SUBJECT} on a turntable, macro lens, large diffused overhead softbox, specular highlight travelling smoothly across the surface, seamless gradient background, tack sharp throughout, no flicker',
  neg='harsh point-source glare, cluttered props, visible fingerprints, uneven background, cheap plastic sheen, distracting reflections of the studio',
  recipe='عکس محصول یعنی <b>کنترل بازتاب</b>. «controlled specular highlights» و «large diffused softbox» جلوی لکه‌های نور تیز را می‌گیرند. «focus stacking» کل سوژه را واضح می‌کند — برای محصول لازم است، برای پرتره نه.',
  tags='محصول تبلیغاتی ماکرو بازتاب استودیو product macro commercial specular focus stacking'),

# ── نقاشی کلاسیک ─────────────────────────────────────────────────────────
S(id='oil', cat='classic', fa='رنگ روغن کلاسیک', en='Classical Oil Painting', period='سده‌ی ۱۷–۱۹',
  plate=('impasto','chiaro',['#3B2A1C','#8A5A2B','#E8C88A','#5E3A1E','#C79A5B']),
  dna=dict(medium='رنگ روغن روی بوم کتانی',
           brush='ضربه‌قلم ضخیم و جهت‌دار، لایه‌ی لعابی روی سایه',
           light='کیاروسکورو از یک پنجره‌ی بلند',
           palette='خاکی گرم: اومبر، اخرا، عاج',
           texture='ایمپاستوی برجسته، بافت بوم دیده می‌شود',
           comp='هرم کلاسیک، سوژه در نور، حاشیه در تاریکی',
           mood='باوقار، گرم، موزه‌ای'),
  subject='an elderly scholar at a desk of open books and a brass astrolabe',
  img='classical oil painting of {SUBJECT}, visible impasto brushwork, glazed transparent shadows, warm earth palette of raw umber and ochre, chiaroscuro lighting from a single high window, aged linen canvas texture, museum photograph',
  vid='camera drifting slowly across an oil painting of {SUBJECT}, raking light revealing impasto ridges and canvas weave, warm earth palette, chiaroscuro falloff, dust in the air, painterly texture consistent throughout, no style drift',
  neg='flat digital gradient, airbrushed surface, neon colour, vector edges, smooth 3D render, photographic skin pores, plastic sheen',
  recipe='سه ستون دارد: <b>ضربه‌قلم دیده‌شود</b>، <b>پالت خاکی گرم</b>، و <b>بافت بوم</b>. اگر خروجی زیادی «دیجیتال» شد، «museum photograph» و «aged canvas texture» را نگه دار — بیشترین اثر را همین دو دارند.',
  tags='اویل رنگ‌روغن کلاسیک رامبراند بوم قلم‌مو oil painting impasto canvas classical'),

S(id='baroque', cat='classic', fa='باروک', en='Baroque', period='سده‌ی ۱۷',
  plate=('impasto','chiaro',['#241611','#7A2E1E','#D9A441','#0E0A08']),
  dna=dict(medium='رنگ روغن روی بوم بزرگ',
           brush='قلم‌زنی کنترل‌شده اما پیدا، لبه‌های نرم در سایه',
           light='تنبریسم — نور تند از یک سو، بقیه در سیاهی',
           palette='قرمز عمیق، طلایی خاموش، قهوه‌ای سوخته',
           texture='سطح نقاشانه با براقی لعاب',
           comp='قطرهای پویا، صحنه‌آرایی تئاتری، حرکت مارپیچ',
           mood='دراماتیک، باشکوه، پرتنش'),
  subject='a lute player leaning into the light, caught mid-chord',
  img='Baroque oil painting of {SUBJECT}, tenebrism with a single hard light source, deep crushed shadows filling most of the frame, dynamic diagonal composition, theatrical staging, rich warm reds and muted gold, luminous flesh tones, controlled painterly brushwork',
  vid='slow theatrical reveal of {SUBJECT} in Baroque light, single hard source raking across the scene, most of the frame held in deep shadow, dynamic diagonal staging, warm reds and muted gold, painterly surface, candle-like flicker on highlights',
  neg='flat even lighting, pastel palette, symmetrical static composition, cartoon outlines, modern clothing, digital gradient sky',
  recipe='باروک با <b>تاریکی</b> ساخته می‌شود نه با نور. «deep crushed shadows filling most of the frame» را حذف نکن، وگرنه مدل همه‌جا را روشن می‌کند. تفاوتش با رنسانس در همین است: رنسانس متعادل و ایستا، باروک قطری و پرحرکت.',
  tags='باروک تنبریسم کاراواجو دراماتیک قطری baroque tenebrism caravaggio dramatic diagonal'),

S(id='renaissance', cat='classic', fa='رنسانس', en='Renaissance', period='سده‌ی ۱۵–۱۶',
  plate=('smooth','soft',['#2E3B34','#9C7A4E','#E4D6B8','#6B4A3A']),
  dna=dict(medium='تمپرا یا رنگ روغن روی پانل چوبی',
           brush='اسفوماتو؛ گذار نامحسوس، ضربه‌قلم پنهان',
           light='نور نرم و یکنواخت از چپ',
           palette='سبز زیتونی، اخرای روشن، آبی آسمانی کم‌رنگ',
           texture='سطح صیقلی، لعاب نازک',
           comp='ترکیب هرمی، تقارن، پرسپکتیو خطی دقیق',
           mood='متعادل، آرام، انسان‌گرا'),
  subject='a young woman holding a quince, seated before an open loggia',
  img='Renaissance painting of {SUBJECT}, sfumato soft transitions with no visible brush marks, balanced pyramidal composition, precise one-point linear perspective, gentle even light from the left, olive green and pale ochre palette, thin glazed panel surface, serene humanist atmosphere',
  vid='stately slow zoom into a Renaissance panel painting of {SUBJECT}, sfumato transitions, balanced pyramidal staging, precise linear perspective receding behind the figure, soft even light, restrained olive and ochre palette, no drift in texture',
  neg='harsh chiaroscuro, loose expressive brushwork, asymmetric chaotic staging, saturated neon, visible impasto, modern background',
  recipe='کلیدش <b>اسفوماتو</b> است: «no visible brush marks». اگر ضربه‌قلم دیده شود دیگر رنسانس نیست. «one-point linear perspective» را هم صریح بگو — رنسانس جایی است که پرسپکتیو ریاضی وارد نقاشی شد.',
  tags='رنسانس اسفوماتو پرسپکتیو داوینچی تعادل renaissance sfumato perspective humanist panel'),

S(id='romantic', cat='classic', fa='رمانتیسم', en='Romanticism', period='سده‌ی ۱۹',
  plate=('impasto','back',['#1B2430','#5C6E7E','#D8B27A','#8A3B2A']),
  dna=dict(medium='رنگ روغن روی بوم',
           brush='آزاد و پرانرژی، آسمان با قلم پهن',
           light='نور طوفانی، شکاف ابر، کنتراست شدید',
           palette='خاکستری آبی سرد در برابر طلایی گرم',
           texture='لایه‌های ضخیم در آسمان، رقیق در دوردست',
           comp='طبیعت عظیم، انسان کوچک و بی‌دفاع',
           mood='حماسی، تنها، سرکش'),
  subject='a lone traveller on a rocky outcrop above a storm-lit valley',
  img='Romantic painting of {SUBJECT}, vast sublime landscape dwarfing a small human figure, stormy sky with a break of golden light, cold blue-grey against warm gold, energetic loose brushwork in the clouds, dramatic atmospheric depth',
  vid='sweeping reveal of {SUBJECT} in a Romantic landscape, storm clouds moving overhead, a shaft of golden light breaking through and travelling across the terrain, tiny human figure for scale, loose painterly sky, immense atmospheric depth',
  neg='tidy pastoral calm, flat lighting, urban setting, tight controlled brushwork, cheerful saturated colour, centred static framing',
  recipe='رمانتیسم درباره‌ی <b>کوچکیِ انسان</b> در برابر طبیعت است. «small human figure» و «sublime» را نگه دار. نورش هم امضا دارد: آسمان طوفانی با یک شکاف طلایی — همان تضاد سرد و گرم.',
  tags='رمانتیسم سابلایم طبیعت طوفان فریدریش romanticism sublime storm landscape friedrich'),

# ── مدرن و انتزاعی ───────────────────────────────────────────────────────
S(id='impressionist', cat='modern', fa='امپرسیونیسم', en='Impressionism', period='۱۸۷۰–۱۸۹۰',
  plate=('dabs','golden',['#7FA5C4','#EBD9A0','#C98BA0','#8FA86E','#F2E2C2']),
  dna=dict(medium='رنگ روغن، نقاشی در فضای باز',
           brush='ضربه‌های کوتاه و جدا از هم، رنگ نامخلوط',
           light='نور طبیعی لکه‌لکه، ساعت‌های روشن روز',
           palette='های‌کی؛ آبی، صورتی، زرد در کنار هم',
           texture='سطح مرتعش، بدون لبه‌ی تیز',
           comp='قاب بریده، انگار لحظه‌ای دزدیده شده',
           mood='زودگذر، روشن، سرزنده'),
  subject='a riverside cafe terrace under summer trees',
  img='Impressionist painting of {SUBJECT}, broken colour applied in short visible dabs of pure unmixed pigment, dappled natural daylight, soft edges dissolving into atmosphere, high-key palette, painted en plein air',
  vid='Impressionist painted sequence of {SUBJECT}, dappled sunlight shifting through moving leaves, short dabs of pure colour shimmering, soft edges throughout, high-key daylight palette, gentle handheld drift, painterly texture stable across frames',
  neg='hard outlines, blended smooth gradients, dark tonal shadows, studio lighting, photographic detail, muddy mixed colour',
  recipe='امپرسیونیسم یعنی <b>نور را نقاشی کن، نه شیء را</b>. «broken colour» و «short dabs» باعث می‌شوند رنگ‌ها کنار هم بنشینند نه مخلوط شوند. اگر خروجی خیلی واضح شد، «soft edges dissolving into atmosphere» را تکرار کن.',
  tags='امپرسیونیسم مونه نور طبیعی ضربه‌قلم impressionist monet plein air broken colour'),

S(id='postimp', cat='modern', fa='پست‌امپرسیونیسم', en='Post-Impressionism', period='۱۸۸۵–۱۹۰۵',
  plate=('impasto','flat',['#1E3A5F','#F2B705','#2E7D5B','#D94F2B']),
  dna=dict(medium='رنگ روغن غلیظ، مستقیم از تیوب',
           brush='ضربه‌های مارپیچ و موجی، جهت‌دار و آگاهانه',
           light='نور نمادین، نه واقعی',
           palette='رنگ خالص و اشباع، تضاد مکمل',
           texture='ایمپاستوی سنگین با شیار قابل لمس',
           comp='فرم ساده‌شده، خط دور کلفت',
           mood='پرشور، ذهنی، پرتنش'),
  subject='a cypress-lined road under a turbulent evening sky',
  img='Post-Impressionist painting of {SUBJECT}, thick swirling directional impasto straight from the tube, saturated complementary colour, simplified bold forms with heavy contour, expressive non-naturalistic light, tactile ridged paint surface',
  vid='Post-Impressionist painted sequence of {SUBJECT}, swirling brush ridges catching the light, saturated complementary colour, forms simplified and outlined, paint surface visibly tactile, slow drifting camera, no smoothing between frames',
  neg='photorealistic detail, muted greys, flat even paint, thin washes, precise anatomy, digital airbrush',
  recipe='تفاوتش با امپرسیونیسم: آنجا رنگ می‌لرزد، اینجا <b>رنگ فریاد می‌زند</b>. «swirling directional impasto» و «saturated complementary colour» دو ستون آن‌اند. نور دیگر واقعی نیست — احساس است.',
  tags='پست امپرسیونیسم ونگوگ ایمپاستو مارپیچ post-impressionism van gogh impasto swirling'),

S(id='artnouveau', cat='modern', fa='آر نوو', en='Art Nouveau', period='۱۸۹۰–۱۹۱۰',
  plate=('line','flat',['#2C4A3E','#C9A227','#D98C6A','#EFE3C8']),
  dna=dict(medium='چاپ سنگی، پوستر رنگی',
           brush='خط پیوسته و موزون، ضخامت متغیر',
           light='بدون سایه‌ی حجمی؛ سطح تخت',
           palette='سبز زیتونی، طلایی، هلویی خاموش',
           texture='مسطح با بافت کاغذ چاپ',
           comp='قاب تزئینی، خطوط تازیانه‌ای، طبیعت گیاهی',
           mood='ظریف، تزئینی، ارگانیک'),
  subject='a woman with long flowing hair holding a spray of irises',
  img='Art Nouveau poster of {SUBJECT}, flowing whiplash contour lines of varying weight, flat decorative colour without volumetric shading, ornamental botanical border framing the composition, muted olive and gold palette, lithographic paper texture',
  vid='Art Nouveau animated poster of {SUBJECT}, flowing contour lines drawing themselves, flat decorative colour fills, ornamental botanical border, limited palette of olive and gold, gentle parallax between the border and the figure, no volumetric shading',
  neg='realistic shading, photographic depth, harsh perspective, gritty texture, neon palette, three-dimensional rendering',
  recipe='آر نوو <b>حجم ندارد</b> — «flat decorative colour without volumetric shading». امضایش خط «whiplash» است: خطی پیوسته با ضخامت متغیر که مثل ساقه‌ی گیاه می‌پیچد. قاب تزئینی را حذف نکن، بخشی از سبک است.',
  tags='آرنوو موشا پوستر تزئینی گیاهی art nouveau mucha poster whiplash ornamental'),

S(id='artdeco', cat='modern', fa='آر دکو', en='Art Deco', period='۱۹۲۰–۱۹۳۹',
  plate=('flat','top',['#0E1D2B','#C9A227','#8C1C2B','#E8E1D2']),
  dna=dict(medium='پوستر چاپی، رنگ تخت',
           brush='لبه‌ی تیز و مکانیکی',
           light='نور نمادین، پرتوهای هندسی',
           palette='سرمه‌ای، طلا، قرمز آجری، کرم',
           texture='کاملاً صاف، بدون بافت',
           comp='تقارن، پله‌های هندسی، خطوط سرعت',
           mood='مدرن، مقتدر، پرشکوه'),
  subject='an ocean liner seen from a pier at dawn, two travellers watching',
  img='Art Deco poster of {SUBJECT}, strict symmetry, stepped geometric forms, sharp mechanical edges, flat colour fills in navy gold brick red and cream, stylised speed lines, streamlined machine-age elegance, no texture',
  vid='Art Deco motion poster of {SUBJECT}, symmetrical stepped geometry assembling into place, flat colour fills, gold linework catching a sweep of light, stylised speed lines, machine-age precision, absolutely flat surfaces',
  neg='organic irregular shapes, painterly texture, soft focus, pastel palette, hand-drawn wobble, photographic realism',
  recipe='آر دکو دقیقاً <b>مقابل</b> آر نووست: آنجا ارگانیک و پیچان، اینجا هندسی و متقارن. «stepped geometric forms» و «strict symmetry» را نگه دار. بافت نداشته باشد — «no texture» را بنویس.',
  tags='آردکو هندسی متقارن طلایی ماشینی art deco geometric symmetry streamline gatsby'),

S(id='surreal', cat='modern', fa='سوررئالیسم', en='Surrealism', period='۱۹۲۴ به بعد',
  plate=('smooth','golden',['#1B2A4A','#D9A05B','#8C4A5E','#E8DCC0']),
  dna=dict(medium='رنگ روغن با پرداخت آکادمیک',
           brush='بسیار دقیق و صیقلی — تا باور شود',
           light='نور رؤیایی، سایه‌های بلند و غیرممکن',
           palette='آبی عمیق، اخرای بیابانی، افق روشن',
           texture='صاف و بی‌درز',
           comp='افق خالی، اشیاء بی‌ربط کنار هم، مقیاس غلط',
           mood='خواب‌گونه، ناآرام، بی‌زمان'),
  subject='a single open door standing alone in an empty desert',
  img='Surrealist oil painting of {SUBJECT}, academically precise rendering of an impossible scene, vast empty horizon, unexpected juxtaposition and shifted scale, long dreamlike shadows, deep blue sky against desert ochre, seamless smooth finish',
  vid='Surrealist sequence of {SUBJECT}, impossible geometry rendered with academic precision, vast empty horizon, long shadows stretching in the wrong direction, objects drifting slowly against gravity, dreamlike stillness, seamless smooth painted surface',
  neg='loose sketchy brushwork, cluttered composition, cartoon exaggeration, obvious digital collage seams, neon cyberpunk palette',
  recipe='رازش این است که <b>هرچه دقیق‌تر کشیده شود، ناآرام‌کننده‌تر است</b>. «academically precise» را نگه دار — سوررئالیسمِ شلخته کار نمی‌کند. سه ابزارش: افق خالی، مقیاس غلط، و کنارهم‌نشینی بی‌ربط.',
  tags='سوررئال دالی مگریت رؤیا افق surrealism dali magritte dreamlike juxtaposition'),

S(id='concept', cat='modern', fa='کنسپت‌آرت سینمایی', en='Cinematic Concept Art', period='معاصر',
  plate=('smooth','back',['#141A22','#3E6C8E','#F0A868']),
  dna=dict(medium='نقاشی دیجیتال، قلم‌موی بافت‌دار',
           brush='نقاشانه و آزاد در دوردست، دقیق در نقطه‌ی کانونی',
           light='نور پشت‌سری، مه اتمسفری بین لایه‌ها',
           palette='کم‌اشباع سرد با یک لکه‌ی گرم',
           texture='نرم و مه‌آلود، جزئیات فقط جایی که لازم است',
           comp='نمای معرف عریض، فیگور کوچک برای مقیاس',
           mood='عظیم، تنها، پیش‌رونده'),
  subject='a ruined observatory dome on a cliff above a fogged valley',
  img='cinematic concept art of {SUBJECT}, wide establishing composition, atmospheric depth haze separating each plane, strong silhouette reading, painterly digital brushwork, moody desaturated palette with one warm accent, tiny human figure for scale, matte painting quality',
  vid='cinematic concept sequence of {SUBJECT}, slow wide establishing move, atmospheric haze separating distant planes, strong silhouettes, one warm accent light in a desaturated frame, tiny figure for scale walking into the shot, painterly texture held steady',
  neg='cluttered foreground, flat lighting, saturated rainbow palette, cartoon proportions, busy detail everywhere, missing sense of scale',
  recipe='کنسپت‌آرت با <b>سیلوئت و مقیاس</b> کار می‌کند. «tiny human figure for scale» تک‌تنه حس عظمت می‌سازد و «atmospheric depth haze» عمق می‌دهد. قانون رنگش: همه‌چیز کم‌اشباع، فقط <b>یک</b> لکه‌ی گرم.',
  tags='کنسپت آرت سینمایی مت‌پینتینگ عظمت concept art matte painting cinematic scale silhouette'),

# ── سنتی و شرقی ──────────────────────────────────────────────────────────
S(id='miniature', cat='trad', fa='مینیاتور ایرانی', en='Persian Miniature', period='صفوی · سده‌ی ۱۶',
  plate=('flat','flat',['#0E3E52','#C9A227','#1E5B70','#8C2F39']),
  dna=dict(medium='رنگدانه‌ی معدنی و طلا روی کاغذ',
           brush='قلم‌موی بسیار نازک، خط یکدست',
           light='بدون منبع نور واحد؛ همه‌جا روشن',
           palette='لاجورد، فیروزه، شنگرف، طلا',
           texture='مسطح و درخشان، بدون سایه‌ی حجمی',
           comp='بدون نقطه‌ی گریز؛ صحنه از بالا باز می‌شود، قاب تذهیب',
           mood='جواهرگون، موزون، بی‌زمان'),
  subject='a prince listening to a musician beneath a blossoming tree in a walled garden',
  img='Persian miniature painting of {SUBJECT}, flattened perspective with no vanishing point, scene opening upward rather than receding, intricate gold leaf detailing, lapis lazuli blue turquoise and vermilion, ornamental illuminated border, fine even brush linework, Safavid manuscript page',
  vid='Persian miniature scene of {SUBJECT} coming to life, flattened space with no vanishing point, gold leaf catching a slow sweep of light, lapis and vermilion holding saturation, ornamental border framing every frame, figures moving with flat rhythmic grace, no perspective drift',
  neg='western one-point perspective, volumetric shadows, muted earth palette, oil impasto texture, photographic depth of field, generic middle-eastern pastiche',
  recipe='مینیاتور <b>پرسپکتیو ندارد</b> — «no vanishing point» چیزی است که مدل همیشه فراموش می‌کند. سه رنگ امضایش: لاجورد، شنگرف، طلا. و صحنه به‌جای عقب رفتن، <b>رو به بالا باز می‌شود</b>؛ همین را هم بنویس.',
  tags='مینیاتور ایرانی نگارگری صفوی تذهیب لاجورد شنگرف نسخه خطی persian miniature safavid gold lapis'),

S(id='qajar', cat='trad', fa='نقاشی قاجار', en='Qajar Painting', period='سده‌ی ۱۹',
  plate=('smooth','flat',['#2B1A2E','#C1362F','#D9B45B','#3E6B57']),
  dna=dict(medium='رنگ روغن روی بوم، تأثیر اروپایی',
           brush='صیقلی با جزئیات تزئینی بسیار ریز',
           light='نور یکنواخت جلویی، سایه‌ی کم',
           palette='قرمز یاقوتی، سبز زمردی، طلا، سیاه',
           texture='سطح براق، جواهر و پارچه پرجزئیات',
           comp='فیگور تمام‌قد رو به بیننده، تقارن درباری',
           mood='باشکوه، رسمی، تزئینی'),
  subject='a court musician standing full length holding a tar',
  img='Qajar-era Persian oil painting of {SUBJECT}, frontal full-length courtly figure, even frontal light with minimal shadow, ruby red emerald green and gold palette, extremely detailed textiles jewellery and ornament, polished surface, formal symmetrical staging',
  vid='Qajar court portrait of {SUBJECT} in slow motion, frontal even light, ruby and emerald textiles catching gold thread, jewellery glinting, formal symmetrical staging held, ornament rendered in fine detail, minimal shadow throughout',
  neg='dramatic chiaroscuro, loose impressionist brushwork, casual candid pose, muted palette, western renaissance sfumato',
  recipe='قاجار جایی است که رنگ روغن اروپایی با تزئین ایرانی ترکیب شد. برخلاف مینیاتور، <b>حجم دارد</b> — ولی نورش جلویی و یکنواخت است، نه کیاروسکورو. جزئیات پارچه و جواهر امضای آن است.',
  tags='قاجار درباری ایرانی پرتره تزئین qajar persian court portrait ornament nineteenth century'),

S(id='ukiyoe', cat='trad', fa='اوکیو-ئه ژاپنی', en='Ukiyo-e', period='سده‌ی ۱۷–۱۹',
  plate=('flat','flat',['#1B3A5C','#D96A5B','#E8DCC0','#3E6B57']),
  dna=dict(medium='چاپ چوبی، مرکب آبی و رنگدانه‌ی گیاهی',
           brush='خط دور یکدست و مطمئن',
           light='بدون سایه؛ سطوح تخت',
           palette='آبی پروس، صورتی مرجانی، خردلی، کرم کاغذ',
           texture='دانه‌ی چوب و بافت کاغذ واشی',
           comp='قاب برش‌خورده، منحنی‌های بزرگ، فضای منفی جسورانه',
           mood='آرام، موزون، تخت'),
  subject='a traveller crossing a wooden bridge in driving rain',
  img='Japanese ukiyo-e woodblock print of {SUBJECT}, confident even outline, flat colour areas with no shading, Prussian blue coral pink and mustard on cream washi paper, visible woodgrain texture, bold cropping and generous negative space, layered flat planes',
  vid='ukiyo-e woodblock scene of {SUBJECT}, flat colour planes sliding as layers, confident black outlines, Prussian blue and coral holding flat, visible paper grain, stylised repeating wave and cloud motion, absolutely no volumetric shading',
  neg='volumetric shading, western perspective depth, photographic texture, airbrushed gradients, saturated digital neon, three-dimensional lighting',
  recipe='اوکیو-ئه <b>سایه ندارد</b> و با «خط دور + سطح تخت» ساخته می‌شود. «Prussian blue» تصادفی نیست — رنگدانه‌ای وارداتی بود که امضای این چاپ‌ها شد. برش جسورانه‌ی کادر هم بخشی از سبک است.',
  tags='اوکیوئه ژاپنی چاپ چوبی هوکوسای موج ukiyo-e japanese woodblock hokusai prussian blue'),

S(id='inkwash', cat='trad', fa='مرکب چینی', en='Chinese Ink Wash', period='سنتی',
  plate=('wash','flat',['#F2F0E9','#4A4A4A','#1A1A1A','#8C8C8C']),
  dna=dict(medium='مرکب بر پایه‌ی دوده روی کاغذ شوان',
           brush='یک ضربه‌ی قطعی و بازگشت‌ناپذیر',
           light='بدون نور جهت‌دار؛ ارزش با غلظت مرکب',
           palette='تک‌رنگ، از سیاه غلیظ تا خاکستری آبکی',
           texture='دویدن مرکب روی کاغذ جاذب',
           comp='فضای خالی بیشتر از پُر؛ خلأ معنا دارد',
           mood='مراقبه‌ای، خویشتن‌دار، شاعرانه'),
  subject='a fisherman poling a narrow boat between misted peaks',
  img='Chinese ink wash painting of {SUBJECT}, single decisive unrepeatable brushstrokes, monochrome ink from dense black to pale grey wash, ink bleeding into absorbent xuan paper, vast areas of deliberate empty space, misty layered mountains receding into nothing',
  vid='Chinese ink wash scene of {SUBJECT}, ink blooming into paper in real time, monochrome values only, mist drifting between layered planes, vast empty space held in the frame, single decisive strokes appearing, no colour at any point',
  neg='colour, dense detail everywhere, hard mechanical edges, photographic texture, filled background, western shading',
  recipe='این سبک با <b>خالی</b> ساخته می‌شود. «vast areas of deliberate empty space» را حذف نکن، وگرنه مدل کادر را پر می‌کند و همه‌چیز از بین می‌رود. «monochrome» را هم صریح بنویس.',
  tags='مرکب چینی شوان کوهستان مه تک‌رنگ chinese ink wash sumi xuan monochrome mountains'),

# ── متریال و تکنیک ───────────────────────────────────────────────────────
S(id='watercolor', cat='tech', fa='آبرنگ', en='Watercolour', period='—',
  plate=('wash','soft',['#F2EFE6','#8FC7D8','#D98C9B','#A8C6A1']),
  dna=dict(medium='آبرنگ روی کاغذ فشرده‌ی سرد',
           brush='واش آزاد، لبه‌ی خیس‌در‌خیس',
           light='روشنایی از کاغذ می‌آید، نه از رنگ',
           palette='پاستل کم‌اشباع، شفاف',
           texture='دانه‌ی کاغذ و رسوب رنگدانه',
           comp='سوژه شناور در سفیدی',
           mood='سبک، لطیف، بی‌شتاب'),
  subject='a quiet harbour with three moored fishing boats',
  img='delicate watercolour painting of {SUBJECT}, wet-on-wet bleeding edges, visible cold-press paper grain, pigment granulation settling in the texture, large areas of untouched white paper, loose confident washes, muted pastel palette',
  vid='watercolour illustration of {SUBJECT} coming alive, pigment blooming into damp paper, edges softening and settling, large areas of paper left white, granulation visible in the wash, gentle breathing motion, paper texture constant',
  neg='opaque flat colour, digital airbrush, hard vector edges, dark heavy shadows, fully painted background, oil impasto',
  recipe='آبرنگ با <b>چیزی که رنگ نشده</b> تعریف می‌شود. «untouched white paper» را حذف نکن وگرنه خروجی مثل نقاشی دیجیتال سنگین می‌شود. «wet-on-wet» لبه‌ی نرم می‌سازد؛ برای لبه‌ی تیزتر «wet-on-dry» بنویس.',
  tags='آبرنگ واترکالر کاغذ واش شفاف watercolour aquarelle wet-on-wet paper granulation'),

S(id='gouache', cat='tech', fa='گواش و پوستر رترو', en='Gouache / Retro Poster', period='میانه‌ی سده‌ی ۲۰',
  plate=('flat','flat',['#2B4162','#E4572E','#F4D35E','#EFE7D8']),
  dna=dict(medium='گواش مات روی مقوا',
           brush='سطح یکدست، بدون گذار',
           light='نور نمادین، سایه به شکل لکه‌ی رنگی',
           palette='حداکثر چهار رنگ',
           texture='مات و مخملی، بافت چاپ کاغذ',
           comp='فرم ساده‌شده، ترکیب پوستر سفر',
           mood='خوش‌بین، گرافیکی، نوستالژیک'),
  subject='a mountain railway station beneath a snow peak',
  img='mid-century gouache poster illustration of {SUBJECT}, flat matte colour blocks, limited four-colour palette, bold simplified shapes, subtle paper print texture, slight halftone misregistration, travel poster composition',
  vid='mid-century gouache poster of {SUBJECT} animated, flat matte colour blocks shifting as cut shapes, four-colour palette held, halftone misregistration shimmering slightly, paper texture constant, no gradients at any point',
  neg='photographic gradient, soft airbrush blending, realistic shading, more than five colours, glossy digital sheen',
  recipe='گواش با <b>سطوح تخت و مات</b> کار می‌کند نه با سایه‌ی نرم. کلید کنترلش «limited four-colour palette» است — هرچه رنگ کمتر، حرفه‌ای‌تر. «halftone misregistration» حس چاپ قدیمی می‌دهد.',
  tags='گواش پوستر رترو مینیمال چاپ ریسو gouache poster retro flat halftone risograph'),

S(id='graphite', cat='tech', fa='طراحی با مداد', en='Graphite Sketch', period='—',
  plate=('hatch','flat',['#EDEBE7','#8B8B8B','#2A2A2A']),
  dna=dict(medium='مداد گرافیت روی کاغذ طراحی',
           brush='هاشور متقاطع، محو با انگشت',
           light='ارزش‌گذاری تُنی، بدون رنگ',
           palette='تک‌رنگ خاکستری',
           texture='دانه‌ی کاغذ، براقی گرافیت',
           comp='خطوط راهنما پاک‌نشده، صفحه‌ی دفتر اتود',
           mood='مطالعاتی، صمیمی، ناتمام'),
  subject='two hands resting on a folded cloth',
  img='graphite pencil study of {SUBJECT}, cross-hatched shading building form, visible construction lines left unerased, soft smudged mid-tones, bright paper highlights, tonal value study, sketchbook page, no colour',
  vid='graphite study of {SUBJECT} drawing itself, construction lines laid down first and left visible, cross-hatching building tone in passes, smudged mid-tones, paper grain constant, strictly monochrome',
  neg='colour tint, digital line art, vector precision, painted texture, clean erased construction, photographic detail',
  recipe='چیزی که طراحی مدادی را باورپذیر می‌کند <b>ناتمام بودنش</b> است: «construction lines left unerased». «no colour» را حتماً بنویس، وگرنه مدل ته‌رنگ اضافه می‌کند.',
  tags='مداد طراحی اتود سیاه‌قلم هاشور graphite pencil sketch hatching monochrome construction'),

S(id='woodcut', cat='tech', fa='چاپ چوبی و لینوکات', en='Woodcut / Linocut', period='—',
  plate=('line','flat',['#F0EAD9','#1A1A1A','#B23A2E']),
  dna=dict(medium='چاپ برجسته از بلوک چوب یا لینو',
           brush='کنده‌کاری با اسکنه؛ خط ضخیم و بریده',
           light='بدون تُن میانی؛ فقط سیاه و سفید',
           palette='سیاه روی کاغذ کرم، گاهی یک رنگ دوم',
           texture='لبه‌ی خشن، جوهر ناهموار',
           comp='کنتراست شدید، فرم ساده و قدرتمند',
           mood='خام، پرقدرت، مردمی'),
  subject='a farmer and an ox turning a furrow',
  img='woodcut print of {SUBJECT}, bold gouged lines carved with a chisel, stark black ink on cream paper with no mid-tones, rough irregular edges where the block bit, uneven ink coverage, high contrast simplified forms, single spot colour',
  vid='woodcut print of {SUBJECT} printing itself stroke by stroke, carved lines appearing, stark black on cream with no mid-tones, uneven ink texture, rough block edges, one spot colour registering slightly off',
  neg='smooth gradients, grey mid-tones, fine airbrush detail, photographic realism, digital vector cleanliness, pastel palette',
  recipe='چاپ چوبی <b>خاکستری ندارد</b> — «no mid-tones» را بنویس. زیبایی‌اش در نقص است: «rough irregular edges» و «uneven ink coverage». اگر تمیز و یکدست شود، دیگر چاپ دستی نیست.',
  tags='چاپ چوبی لینوکات گراوور کنده‌کاری woodcut linocut relief print carved high contrast'),

# ── نورپردازی ────────────────────────────────────────────────────────────
S(id='golden', cat='light', fa='نور طلایی (گلدن آور)', en='Golden Hour', period='—',
  plate=('smooth','golden',['#2A1B14','#C9743B','#FFD9A0']),
  dna=dict(medium='—', brush='—',
           light='خورشید پایین و پشت سوژه، پرتوهای مایل',
           palette='کهربایی گرم، دمای رنگ حدود ۳۲۰۰ کلوین',
           texture='ذرات معلق در پرتو نور',
           comp='سایه‌های بلند و کشیده',
           mood='گرم، نوستالژیک، زودگذر'),
  subject='a woman in a long dark coat walking through tall dry grass',
  img='{SUBJECT} lit by low golden hour sun, long raking shadows, warm amber key light from behind, hazy atmospheric backlight, dust motes catching the light, soft lens flare, warm 3200K colour temperature',
  vid='{SUBJECT} in golden hour, low sun behind the subject, long shadows sweeping as the camera moves, dust motes drifting through the beam, soft flare blooming and receding, warm amber grade held steady, light falling slowly as the shot runs',
  neg='midday overhead sun, cool blue cast, flat shadowless light, studio strobe, harsh clinical white balance',
  recipe='گلدن آور یعنی خورشید <b>پایین و پشت سوژه</b>. «low sun» و «from behind» را با هم بنویس وگرنه نور از روبه‌رو می‌تابد. «dust motes» و «haze» پرتو را <em>دیدنی</em> می‌کنند — بدون ذره‌ی معلق، نور دیده نمی‌شود.',
  tags='گلدن آور نور طلایی غروب کنتره گرم golden hour warm sunset backlight haze flare'),

S(id='chiaro', cat='light', fa='کیاروسکورو', en='Chiaroscuro', period='—',
  plate=('smooth','chiaro',['#0A0A0C','#5E4632','#F0DDBC']),
  dna=dict(medium='—', brush='—',
           light='یک منبع سخت از بالا-چپ، افت شدید',
           palette='سیاه له‌شده با یک حوضچه‌ی گرم',
           texture='—',
           comp='بیشتر کادر در تاریکی، سوژه در نور',
           mood='دراماتیک، رازآلود، متمرکز'),
  subject='a woman in a long dark coat turning her face toward the light',
  img='{SUBJECT} in dramatic chiaroscuro, single hard light source from upper left, deep crushed blacks occupying most of the frame, sharp falloff, small pool of illumination, high contrast ratio 8:1',
  vid='{SUBJECT} in chiaroscuro, one hard source from upper left, most of the frame in crushed black, the subject moving through the pool of light and partly out of it, sharp falloff at the edges, contrast held at 8:1, no fill light',
  neg='soft even fill, multiple light sources, bright background, low contrast, flat ambient illumination',
  recipe='این سبک با <b>تاریکی</b> ساخته می‌شود نه با نور. «deep crushed blacks occupying most of the frame» را حتماً بگو، وگرنه مدل همه‌جا را روشن می‌کند. «single hard light source» یعنی فقط یکی — دو منبع، کیاروسکورو را نابود می‌کند.',
  tags='کیاروسکورو کاراواجو نور تک منبع کنتراست chiaroscuro caravaggio rembrandt hard light tenebrism'),

S(id='neon', cat='light', fa='نئون شبانه', en='Neon Night', period='—',
  plate=('smooth','neon',['#0B0F1A','#FF2E63','#22D3EE']),
  dna=dict(medium='—', brush='—',
           light='فقط تابلوهای نئون؛ دو رنگ مکمل',
           palette='سرخابی و فیروزه‌ای در سیاهی',
           texture='مه سبک که نور را پخش می‌کند',
           comp='حوضچه‌های نور با تاریکی بینشان',
           mood='شهری، بی‌قرار، سینمایی'),
  subject='a woman in a long dark coat on a rain-wet street corner',
  img='{SUBJECT} at night lit only by neon signage, magenta and cyan colour separation, wet asphalt reflections doubling the light, light fog diffusing the glow, deep shadows between the pools of light, fast lens wide open',
  vid='{SUBJECT} walking at night under neon, magenta and cyan separating across the frame, wet asphalt reflecting the signs, fog catching the glow, subject passing through pools of light and into shadow between them, handheld drift, shallow focus',
  neg='daylight, warm tungsten interior, dry clean streets, even ambient fill, desaturated grey palette',
  recipe='نئون بدون <b>سطح بازتابنده و مه</b> کار نمی‌کند — «wet asphalt» و «light fog» نور را دیدنی می‌کنند. دو رنگ مکمل انتخاب کن و «deep shadows between light pools» را نگه دار تا صحنه یکدست روشن نشود.',
  tags='نئون شب سایبرپانک بازتاب مه neon night cyberpunk reflection fog magenta cyan'),

S(id='window', cat='light', fa='نور نرم پنجره', en='Soft Window Light', period='—',
  plate=('smooth','soft',['#E8E4DC','#A8B2B8','#4A4E52']),
  dna=dict(medium='—', brush='—',
           light='نور غیرمستقیم شمالی از پنجره‌ی بزرگ',
           palette='خنثی و آرام، کم‌اشباع',
           texture='—',
           comp='افت ملایم روی سوژه، بازتاب سفید در سمت سایه',
           mood='آرام، خانگی، صمیمی'),
  subject='a woman in a long dark coat seated at a bare table',
  img='{SUBJECT} beside a large north-facing window, soft directional daylight, gentle gradient falloff across the subject, white bounce fill on the shadow side, calm muted palette, quiet domestic mood',
  vid='{SUBJECT} beside a large north-facing window, soft directional daylight unchanging, gentle falloff across the subject, white bounce opening the shadow side, slow quiet camera, calm muted palette, no artificial light',
  neg='hard direct sun, coloured gels, dramatic shadow, studio strobe, high contrast, busy background',
  recipe='نرم‌ترین و قابل‌اعتمادترین نور برای هر سوژه‌ای. «north-facing» یعنی نور غیرمستقیم و یکنواخت. «white bounce fill» سایه را باز می‌کند — اگر سایه‌ی عمیق‌تر خواستی، همین را حذف کن.',
  tags='نور پنجره نرم روزانه ورمیر آرام window light soft daylight vermeer bounce fill'),

S(id='rim', cat='light', fa='بک‌لایت و نور لبه', en='Rim / Backlight', period='—',
  plate=('smooth','rim',['#08090C','#1F3A4D','#BFE3FF']),
  dna=dict(medium='—', brush='—',
           light='منبع پشت سوژه، خط نور روی کانتور',
           palette='سرد و تک‌رنگ، سوژه تقریباً سیاه',
           texture='مه برای جداسازی',
           comp='سیلوئت با لبه‌ی روشن',
           mood='مرموز، حماسی، گرافیکی'),
  subject='a woman in a long dark coat standing in an open doorway',
  img='{SUBJECT} in near silhouette against a bright background, strong rim light tracing the contour, minimal fill on the front, atmospheric haze separating subject from background, high dynamic range, dramatic separation',
  vid='{SUBJECT} in near silhouette, strong rim light tracing the contour as they move, minimal frontal fill, haze separating them from a bright background, the light edge shifting with the motion, dramatic separation held',
  neg='flat frontal lighting, fully lit face, dark background, no atmosphere, low contrast',
  recipe='نور لبه <b>شکل</b> می‌سازد نه جزئیات. «minimal fill on the front» را نگه دار — اگر جلوی سوژه روشن شود سیلوئت می‌شکند. «haze» لازم است تا خط نور از پس‌زمینه جدا شود.',
  tags='بک‌لایت کنتره سیلوئت نور لبه rim light backlight silhouette separation haze'),
]
